### PR TITLE
Allow custom mods

### PR DESCRIPTION
**Pull request by Tiebe**
This will allow adding custom mods by putting jars in .minecraft/SolarMods

Still very much a WIP

### CODE REVIEW

**Comment by mjkzy** [comment]
> Hey, can you tell us what are you trying to do? Maybe we can help :D

Pretty sure he is trying to make some sort of system where you could load your own custom jars from a directory and it's basically mods you can use with MC, like forge mods?

**Comment by Tiebe** [comment]
> > Hey, can you tell us what are you trying to do? Maybe we can help :D
> 
> Pretty sure he is trying to make some sort of system where you could load your own custom jars from a directory and it's basically mods you can use with MC, like forge mods?

Yep exactly this, I'm already working with @770grappenmaker, but I really appreciate any help

**Comment by Tiebe** [comment]
I'm using Java for now, since I'm much more comfortable with it. I'll convert all the files later. 

Also, does anyone know how it can serialize and (more importantly) deserialize a class using `kotlinx.serialization`? I couldn't seem to figure it out so I just used Gson for now. 

Btw, I haven't been able to test this code yet, so there are probably bugs in it.

**Comment by 770grappenmaker** [comment]
@Tiebe

**Comment by Tiebe** [comment]
Sorry, I was busy with other things and completely forgot about this project. I'll get back to it!

**Comment by 770grappenmaker** [comment]
If you dont want to work on it you dont have to ofc

**Comment by Tiebe** [comment]
No I love the project, just haven't had as much time!

**Comment by robigan** [comment]
So is this being maintained or what? Cus I'd like to patch my own custom mod (written in Java) in for usage with LunarClient

**Comment by WindLeaf233** [comment]
does this pr still in progress? i find that there's a long time no update here

**Comment by Tiebe** [comment]
I would love to continue this, but I don't really play much anymore. If anyone would like to continue my work, you can fork my branch

**Comment by robigan** [comment]
I mean, theoretically speaking, if I were to implement this PR, what would it take for a newby to the codebase to get this PR approved. Cus I don't think this is just a good first issue is it?

**Comment by 770grappenmaker** [comment]
> I mean, theoretically speaking, if I were to implement this PR, what would it take for a newby to the codebase to get this PR approved. Cus I don't think this is just a good first issue is it?

If you wrote working, useful, readable kotlin code then I would merge. No, this is not a good first issue, considering custom mods don't even work anymore

**Pull request closed without merging**
